name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build

      # Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Deploy to Vercel (preview mode)
      - name: Deploy to Vercel (Preview)
        id: vercel
        run: |
          vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}
          vercel build --token=${{ env.VERCEL_TOKEN }}
          preview_url=$(vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }})
          echo "preview-url=$preview_url" >> $GITHUB_OUTPUT

      # Sticky PR comment with the preview URL
      - name: Post/Update PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            🚀 **Preview ready**
            URL: ${{ steps.vercel.outputs.preview-url }}

      # Optional: add as Job Summary in the Checks tab
      - name: Job summary
        run: |
          echo "### Preview URL" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.vercel.outputs.preview-url }}" >> $GITHUB_STEP_SUMMARY
